name: Deploy app nodle com github actions

on:
    push:
            branches:
                - main

jobs:
    build-and-deploy:
        run-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build da imagem Docker
      run: docker build -t hello-world-node .

    - name: Finalizar
      run: echo "Build concluído. Render detectará o push e fará o deploy automaticamente."